services:
  - type: web
    name: toeic-backend
    env: docker
    region: oregon
    branch: main
    rootDir: toeic
    dockerfilePath: ./Dockerfile
    plan: free  # Hoặc "starter" nếu bạn dùng gói khác
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://toeic-mysql:3306/toeic_db?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: Long1907@

databases:
  - name: toeic-mysql
    databaseName: toeic_db
    user: root
    password: Long1907@
    region: oregon
